name: go

on: ['pull_request']

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
           go-version: 1.14
           run: go mod tidy && make
      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0
